### ISSUE TITLE
Getting an error while running this script -ou cannot call a method on a null-valued expression. At line:21 char:1 + $fileEntries = (Get-WmiObject Win32_TSLicenseReport | Where-Object Fi ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException     + FullyQualifiedErrorId : InvokeMethodOnNull

### ISSUE THREAD

**Issue by AminJSyed** [philpug/Powershell_scripts#2]
you cannot call a method on a null-valued expression.
At line:21 char:1
+ $fileEntries = (Get-WmiObject Win32_TSLicenseReport | Where-Object Fi ...

==========

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

==============

**Comment by philpug** [comment]
Hi,

Are you running it on the licence server or another server?
